name: Build and deploy to PI cluster
on:
  push:
    branches:
    - 'master'
    - 'develop'

    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Prepare
        id: prep
        run: |
          TAG=null
          image=timtor/blog
          ref="${{ github.ref }}"

          if [[ "$ref" == refs/heads/* ]]; then
            branch="${ref#refs/heads/}"

            if [ "$branch" = "master" ]; then
              TAG="$image:edge"              
            elif [ "$branch" = "develop" ]; then
              TAG="$image:dev"
            fi

          elif [[ "$ref" == refs/tags/* ]]; then
            version="${ref#refs/tags/}"
            TAG="$image:$version,$image:latest"
          fi

          echo ::set-output name=tag::${TAG}

      - name: Checkout
        uses: actions/checkout@v2.3.4

      # defaultly install all platforms
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          driver-opts: image=moby/buildkit:master

      - name: Login to Docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:  
          context: . 
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.prep.outputs.tag }}

  deploy:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout - cluster repo
        uses: actions/checkout@v2.3.4
        with:
          repository: timtorchen/hola-pi-cluster

      - name: Setup - kubeconfig
        run: |
          mkdir ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      - name: Setup - kubectl, helm, and helmfile
        uses: mamezou-tech/setup-helmfile@v0.5.0

      - name: Setup - helm plugins
        run: |
          helm plugin install https://github.com/aslafy-z/helm-git
          helm plugin install https://github.com/zendesk/helm-secrets

      - name: Setup - GPG private key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Init - helm repos
        run: |
          helmfile repos
      
      - name: Deploy - blog draft 
        if: github.ref == 'refs/heads/develop'
        run: |
          helmfile -l name=blog-draft sync --skip-deps
      
      - name: Deploy - blog
        if: contains( github.ref, 'refs/tags/' )
        run: | 
          helmfile -l name=blog sync --skip-deps
    
      # TODO: change to github marketplace
      - name: Post Setup - kubeconfig
        run: |
          rm ~/.kube/config
